commonLabels:
  label-for: chichao-only

ingress:
  enabled: true
  pathType: Prefix
  hostname: chichao-hc.sctp-sandbox.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "chichao-hc.sctp-sandbox.com"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  tls: true